# Site settings
title: γνώση
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blog in financial markets, trading, and more broadly information processing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jli05.github.io" # the base hostname & protocol for your site
twitter_username: jli05
github_username:  jli05

# Build settings
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge 

gems: [jekyll-paginate]
paginate: 50 
paginate_path: "page:num"

